version: '3.8'

# included for testing against Ray-Worker only
services:
  # Message Queues
  kafka:
    image: bitnami/kafka:3.4.1
    env_file:
      - project.env

  # Object Storage
  minio:
    image: minio/minio:RELEASE.2023-10-07T15-07-38Z
    entrypoint: /usr/bin/docker-entrypoint.sh server /data --console-address :${MINIO_HTTP_PORT}
    ports:
      - ${MINIO_HTTP_PORT}:${MINIO_HTTP_PORT}
    env_file:
      - project.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 20s
      start_period: 10s
      retries: 3
    volumes:
      - "data_mino_ray-worker:/data"

  ray_cast_iron_worker:
    build:
      context: .
    container_name: ray-cast-iron-worker
    env_file:
      - project.env
    shm_size: '6gb'
    volumes:
      - ./etl:/app/etl
    depends_on:
      minio:
        condition: service_healthy

volumes:
  data_mino_ray-worker:
