[tool.poetry]
name = "ray-worker"
version = "2.0.0"
description = ""
authors = ["Ken <ken@blackcape.io>"]

packages = [
    { include = "etl"}
]

[tool.poetry.dependencies]
python = ">=3.8,<3.12"
kafka-python = "<2.0.0"
pydantic = "^1.9.0"
fastapi = "^0.77.1"
toml = "^0.10.2"
minio = "^7.1.8"
uvicorn = "^0.17.6"
psutil = "^5.9.0"
aioch = "^0.0.2"
ray = "^2.7.1"

[tool.poetry.dev-dependencies]
pylint = "^2.15.0"
yapf = "^0.32.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
